apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
  labels:
    app: myapp-app
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: demo
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        tier: demo
    spec:
      containers:
      - name: myapp-contianer
        image: oludocker/my-nodejs-app
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort